---
version: v1
application:
  cluster: shipatlas
  tasks:
    - name: hub-asset-sync
      containers:
        - asset-sync
    - name: hub-database-migrate
      containers:
        - rails
  services:
    - name: hub-web-server
      containers:
        - rails
    - name: hub-worker
      containers:
        - resque
    - name: hub-worker-scheduler
      containers:
        - resque-scheduler
