---
version: v1
cluster: shipatlas
tasks:
  - family: hub-asset-sync
    containers:
      - asset-sync
  - family: hub-database-migrate
    containers:
      - rails
services:
  - name: hub-web-server
    containers:
      - rails
  - name: hub-worker
    containers:
      - resque
  - name: hub-worker-scheduler
    containers:
      - resque-scheduler
