---
version: v1
application:
  cluster: shipatlas
  tasks:
    - name: hub-asset-sync
    - name: hub-database-migrate
  services:
    - name: hub-web-server
    - name: hub-worker
    - name: hub-worker-scheduler
